import 'package:hive/hive.dart';

part 'settings.g.dart'; // This file will be generated by running `flutter pub run build_runner build`

@HiveType(typeId: 0)
class SettingsModal  {
  @HiveField(0)
  late int pomodoro;

  @HiveField(1)
  late int shortBreak;

  @HiveField(2)
  late int longBreak;

  SettingsModal({required this.pomodoro, required this.shortBreak, required this.longBreak});
}